apiVersion: v1
kind: ServiceAccount
metadata:
  name: discord-article-bot
  labels:
    app.kubernetes.io/name: discord-article-bot
    app.kubernetes.io/component: bot
automountServiceAccountToken: false
